### ISSUE TITLE
build a Pump House

### ISSUE THREAD

**Issue by msimerson** [MeanyLodge/Committee#1]
### design requirements

- A person needs to be able to stand inside the shed and work on the well cap, electrical disconnect, or access the reservoir.
- Jim and I paced this off, a 6' x 12' footprint is the minimum that encloses all 3 stubs AND provides adequate working space
    - In the middle of the winter, with a minimum of shoveling snow and/or chiseling ice
- a full height inward swung door (again: snow)
- Access for pulling out the 20-30' long pipes is needed, without destroying the structure (ex: removable roof)
- The reservoir constrains the installation of footings/anchors
- To use footings all around, the structure would have to enclose the reservoir, making it much larger
- Footings can be set on the uphill side
- Meany doesn't need yet another thing to keep painted. Build this to need less maintenance.
- Fire resistant is a nice bonus.

### resources

- Jim pointed me at some 4x12 beams which could rest atop the soil like runners on a sled.

### TODO

- [x] design the building
- [x] pre-build in town
- [x] assemble at Meany lodge
- [x] paint the door & casing
- [x] spray touch up paint on scratches
- [ ] fill (2) holes in roof with silicon caulk
- [x] post a placard with instructions for removing the roof

**Comment by msimerson** [comment]
Since we're building on rails, I opted for pole building construction. Since the rails aren't pressure treated and will rot away, I'll flash the interface between the structure and rails with Vycor so the moisture and rot doesn't wick up to the posts. I'll screw the structure to the rails with framing angles and Simpson structural screws (they are rated for this). In 15-20 years when the rails have rotted away, we can remove the rail screws, tip the shed up and slide in new rails.

My design is light and rigid enough (steel shell helps) that we can remove the fasteners that anchor the uphill side to the concrete piers, put a chain on the two downhill sled rails, and then lift the shed up onto a side. When done, pull it back down and put the nuts back on the anchor threads. At just 1,200 pounds, a couple guys with appropriate levers and blocks could tip it up. Maybe even an enthusiastic herd of free-range teens late one night, "hey duuudes, this thing weights a 1/4 ton less than a VW beetle, if we carry it up the hill, think we can ride it down?!"

<img width="600" alt="Screen Shot 2019-09-09 at 8 48 13 PM" src="https://user-images.githubusercontent.com/261635/68239845-97608680-ffc0-11e9-9260-fefe6d2c99e0.png">

<img width="500" alt="Screen Shot 2019-09-09 at 8 45 09 PM" src="https://user-images.githubusercontent.com/261635/68239858-9c253a80-ffc0-11e9-86b2-a0dabafde1c9.png">

**Comment by msimerson** [comment]
### Chuck saith

> An important design feature needs to be ability to remove the roof in case we need to do maintenance on the well shaft. I live with a well. I know this wont happen often, but if we need that it will be critical. 
>
> I think we can get the structural wood from our stash. I am good with sheet metal roofing and siding with clear panels under the eves. 
>
> I also agree that we want to do GOOD foundation that will last till your kids take over the lodge. 
>
> We might also see if we can get a power outlet installed oit there so we can have light.

**Comment by msimerson** [comment]
### Sep 20th update

I have revised the design per feedback. Changes:

- removable roof. I've attached the roof to the walls with hurricane ties and structural screws. I'll paint the dozen screws that need to be removed, so all that's needed to lift the lid is a cordless drill and a few stout men.
- light: we can tap existing power for light and switch (cheaper, less metal siding scrap, works at night)
	- since its on the trail, we could put motion lights outside the building too?
- I've assembled with minimal screws, I'll finish with additional framing nails during re-assembly at Meany
- I've got 4 days into it: acquiring materials, framing, and trim/siding/detail. I expect to finish pre-assembly in one more day, pre-drill all the holes in the steel, apply all the peel-and-stick flashing, and then disassemble it for transport.

Things that aren't yet addressed that I need help/guidance with:

- I need someone with a pickup to haul it up to Meany. It's about a half a pickup bed of lumber and steel. I'm in Shoreline near the Costco.
- foundation. My knowledge of the pump area is the disturbed soil. I don't have a foundation plan beyond setting the pump house on a couple beams Jim showed me. I was thinking a couple 18" x 3' deep piers that anchor the uphill side of the building would suffice. Thoughts? 
- I'd like a yard of gravel, for use below the concrete and also to set the timbers on. Keeping the timber off the soil greatly slows the wood decay.
- Is there grey flex conduit (water-tite) at the Lodge? That'd be handy to run power from the existing pole over to a switch and then to light fixture(s).
- Do we have threaded rod for setting in the concrete? Plate washers and nuts?
- The door has two holes, for handle and deadbolt. I could drop in an older deadbolt I have laying around. Is there a key policy/schedule for keeping track of locks and keys?

![IMG_0861](https://user-images.githubusercontent.com/261635/68240023-f1f9e280-ffc0-11e9-9ae8-76953742873f.jpeg)

![IMG_0865](https://user-images.githubusercontent.com/261635/68240038-f6be9680-ffc0-11e9-8341-7361d15005da.jpeg)

![IMG_0867](https://user-images.githubusercontent.com/261635/68240044-f9b98700-ffc0-11e9-894e-b8ef10f2d34a.jpeg)

**Comment by msimerson** [comment]
### the Sketchup model

[Meany Pump Shed.skp.zip](https://github.com/MeanyLodge/Committee/files/3811154/Meany.Pump.Shed.skp.zip)

**Comment by msimerson** [comment]
![IMG_3457](https://user-images.githubusercontent.com/261635/162076849-e81db028-317d-491e-9302-e19a11aa691e.jpeg)
