### ISSUE TITLE
replace 1st floor windows

### ISSUE THREAD

**Issue by msimerson** [MeanyLodge/Committee#11]
### ToDo

- [ ] gather dimensions for all windows
- [ ] choose 1 or 2 sizes and have all the windows built
- [ ] reframe the rough openings to match the new window sizes
- [ ] install the windows
