### ISSUE TITLE
2022: Dam repairs / rebuild

### ISSUE THREAD

**Issue by msimerson** [MeanyLodge/Committee#25]
### TODO

- [x] Water pipe inside dam failing, needs attention
- [ ] consider adding mill pond liner to allow easier cleaning
- [x] design and install clean out valve
- [x] Water line between Dam & Cistern subject to freezing, bury under soil for added insulation - either with trench or build up a terrace

**Comment by msimerson** [comment]
> Water line between dam and cistern has been covered and should not freeze anymore.  I will check on that to make sure the winter did not expose it again and recover it if it needs it. -- Michael Froebe
