### ISSUE TITLE
site shipping containers for yard equipment storage

### ISSUE THREAD

**Issue by msimerson** [MeanyLodge/Committee#8]
### goals

- a durable and secure home to park yard equipment
- free up space to enlarge the pantry
- etc.

### todo

- [x] dig trenches along the diesel hut
- [x] pour the east footings and posts
- [ ] pour the west footings and posts
    - [ ] remove the tree whose roots are in the way

**Comment by msimerson** [comment]
Shipping containers require a [permit](https://www.co.kittitas.wa.us/uploads/cds/building/informational-bulletins//Code%20Interpretation%20Policies/18%20-%20CARGO%20CONTAINER%20PLACEMENT.pdf). Our planned foundation supports do not meet the requirements defined in the permits.

**Comment by msimerson** [comment]
- [ ] shipping container roof needs reinforcing to meet snow load (315 lb/sf) requirement
